name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Checkout
        uses: actions/checkout@v2        
        
      - name: Build and push
        id: docker_build_aps
        uses: docker/build-push-action@v2
        with:
          context: ./APs
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wifichallengelab-aps:latest,${{ secrets.DOCKERHUB_USERNAME }}/wifichallengelab-aps:main
          
      - name: Build and push
        id: docker_build_clients
        uses: docker/build-push-action@v2
        with:
          context: ./Clients
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wifichallengelab-clients:latest,${{ secrets.DOCKERHUB_USERNAME }}/wifichallengelab-clients:main
